version: "3.0"
services:

  # Documentation: https://hub.docker.com/_/mariadb
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "hanabi"
      MYSQL_USER: "hanabiuser"
      MYSQL_PASSWORD: "1234567890"
    volumes:
      # Persistent data directory
      - ./mysql_data:/var/lib/mysql
      # First-time initialization
      - ./install/database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql

  # Build the hanabi server from the Dockerfile
  backend:
    build: .
    volumes:
      - ./public:/root/hanabi-live/public
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - 8081:80
