export default interface Settings {
    soundMove: boolean,
    soundTimer: boolean,
    keldonMode: boolean,
    colorblindMode: boolean,
    realLifeMode: boolean,
    reverseHands: boolean,
    styleNumbers: boolean,
    showTimerInUntimed: boolean,
    volume: number,
    speedrunPreplay: boolean,
    speedrunMode: boolean,
    hyphenatedConventions: boolean,
    createTableVariant: string,
    createTableTimed: boolean,
    createTableBaseTimeMinutes: number,
    createTableTimePerTurnSeconds: number,
    createTableSpeedrun: boolean,
    createTableCardCycle: boolean,
    createTableDeckPlays: boolean,
    createTableEmptyClues: boolean,
    createTableCharacterAssignments: boolean,
    createTableAlertWaiters: boolean,

    [key: string]: boolean | number | string,
}
