interface Table {
    id: number,
    name: string,
    password: boolean,
    joined: boolean,
    numPlayers: number,
    owned: boolean,
    running: boolean,
    variant: string,
    timed: boolean,
    baseTime: number,
    timePerTurn: number,
    ourTurn: boolean,
    sharedReplay: boolean,
    progress: number,
    players: string,
    spectators: string,
}
